### ISSUE TITLE
The shell panics on unterminated pipeline with a pipe |

### ISSUE THREAD

**Issue by g1eng** [g1eng/giosh#3]
Now giosh officially supports pipe, but a pipe with an unterminated line does not provide any errors and panics on the exexcution.

```shell
$ ./giosh 
@G[1]> ls -l | 
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
github.com/g1eng/giosh/shell.(*CommandLine).parseStatement(0xc000141cf8, 0x1, 0x6a1fa3)
        /home/suzume/local/Go/giosh/shell/parse_statement.go:23 +0x313
github.com/g1eng/giosh/shell.(*CommandLine).Parse(0xc000141cf8, 0xc00018c000, 0x8)
        /home/suzume/local/Go/giosh/shell/parse.go:9 +0x152
github.com/g1eng/giosh/shell.(*CommandLine).Run(0xc000141cf8, 0x0, 0x5)
        /home/suzume/local/Go/giosh/shell/run.go:26 +0x2bc
github.com/g1eng/giosh/cmd.parseArgs(0xc00005e540, 0x0, 0x1)
        /home/suzume/local/Go/giosh/cmd/parseargs.go:37 +0x625
github.com/urfave/cli/v2.(*App).RunContext(0xc000015380, 0x6f98f0, 0xc00001e060, 0xc000012220, 0x1, 0x1, 0x0, 0x0)
        /home/suzume/go/pkg/mod/github.com/urfave/cli/v2@v2.3.0/app.go:322 +0x6fe
github.com/urfave/cli/v2.(*App).Run(...)
        /home/suzume/go/pkg/mod/github.com/urfave/cli/v2@v2.3.0/app.go:224
github.com/g1eng/giosh/cmd.Cmd()
        /home/suzume/local/Go/giosh/cmd/cmd.go:31 +0x2a8
main.main()
        /home/suzume/local/Go/giosh/main.go:8 +0x25
```

This should be fixed.

**Comment by g1eng** [comment]
With pr #4 , this problem was resolved.
Now unterminated pipe makes an error message and stop the execution (not panic):

```
suzume@mock:~/local/Go/giosh$ ./giosh 
@G[1]> ls -l |
pipe error: pipeline #1 is nil
@G[2]>  
```
